services:
 
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=elastic
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 30s
    deploy:
      resources:
        limits:
          memory: 4g
        reservations:
          memory: 2g
  frontend:
    container_name: nextjs
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - elasticsearch
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 30s

  crawler:
    image: docker.elastic.co/integrations/crawler:${CRAWLER_VERSION:-latest}
    container_name: crawler
    volumes:
      - ./backend/crawler/config:/app/config
    networks:
      - app-network
    stdin_open: true 
    tty: true
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=elastic

volumes:
  elasticsearch-data:

networks:
  app-network:
    driver: bridge
