services:
  crawler:
      image: docker.elastic.co/integrations/crawler:${CRAWLER_VERSION:-latest}
      container_name: crawler
      volumes:
        - ./config:/app/config
      stdin_open: true 
      tty: true
      environment:
        - ELASTICSEARCH_URL=https://es01:${ES_PORT:-9200}
      networks:
        - app-network

networks:
  app-network:
    external: true
