services:
  crawler:
    image: docker.elastic.co/integrations/crawler:${CRAWLER_VERSION:-latest}
    container_name: crawler
    volumes:
      - ./crawler/config:/app/config
    networks:
      - app-network
    stdin_open: true 
    tty: true
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:${ES_PORT:-9200}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}

networks:
  app-network:
    driver: bridge
