# This is an example config for the crawling a web site and storing results in Elasticsearch.
# It is configured to use the ingest pipeline for OpenAI embeddings created while following the setup instructions in the Quickstart guide.
domains:
  - url: https://www.example.com
    sitemap_urls:
      - https://www.example.com/sitemap.xml

output_sink: elasticsearch
output_index: site-index
max_crawl_depth: 2

elasticsearch:
  host: https://es01
  port: 9200
  api_key: <the openai api key from your .env file>
  ca_fingerprint: <the certificate fingerprint for your elasticsearch instance>
  pipeline: openai_embeddings_pipeline # This needs to match the pipeline name in your .env file.
  pipeline_enabled: true