# Run the crawler locally.
#
# This config assumes that the crawler is running in a docker container named `crawler` and that Elasticsearch is running on the same machine.
domains:
  - url: http://host.docker.internal:3002
    
output_sink: elasticsearch
output_index: local-index
private_networks_allowed: true

elasticsearch:
  host: https://es01
  port: 9200
  username: elastic
  password: whateveryourpasswordisbutitsbettertousean
  ca_fingerprint: AB:CD:EF:12:34:...